### ISSUE TITLE
I cannot add more than 50 items

### ISSUE THREAD

**Issue by arfulmeat669** [Jinjinov/IndexedDB.Blazor#1]
**Version**
1.1.1

**OS**
windows visual studio 2019

**Describe the bug**
Hi I'm doing a site for work and I don't know how to store data offline. I found this great library but sadly I can't add more than 50 items in the same table.
can you help me?

**To Reproduce**
1create a table.
2add more than 50 items
**Expected behavior**
no need to add at least 10000 items.

**MY CODE**
``` IndexedDbFactory p = new IndexedDbFactory(DatiPersonaliStatici.JSRuntime);
            using (var db = await p.Create<ContextDb>())
            {
                Console.WriteLine(db.PersonalDate.Count.ToString());
                await db.SaveChanges();
                int startCount = db.PersonalDate.Count;
                for (int i = startCount + 1; i < startCount + 10; i++)
                {
                    DatiPersonaliStatici.Dati.Email = i.ToString();
                    DatiPersonali po = new DatiPersonali();
                    po.Email = i.ToString();
                    po.NomeMacchina = i.ToString();
                    po.LogIsOk = false;
                    po.AutoLogin = false;
                    po.MieiDati = new ClientDatiUtente();
                    po.MieiDati.Mail= i.ToString();
                    po.MieiDati.Token = i.ToString();
                    po.MieiDati.NumeroDiTelefono = i.ToString();
                    po.MieiDati.Nome = i.ToString();
                    po.MieiDati.Cognome = i.ToString();
                    po.MieiDati.IDAzienda = i;
                    po.MieiDati.NumeroTentativiRestanti = i;
                    db.PersonalDate.Add(po);
                }
                await db.SaveChanges(); 

```
**Additional context**
thanks for your patience
![Capture](https://user-images.githubusercontent.com/17816046/114881182-0e7b8a80-9e03-11eb-82d5-414ba5b9e91d.PNG)

**Comment by Jinjinov** [comment]
1. I can't see how your `class PersonalDate` looks like.
2. What is the actual problem? I can see in your image that you have more than 50 items: `Total entries: 63`
3. What does your question mark `?` in the image mean? This is how `string` sorting works in C# - strings are sorted by their first character. If you want your `Key` sorted as number, change `email` from `string` to `int`.

If you provide the necessary details, I will help you, but just this one time - this is not StackOverflow - GitHub issues are meant for actual bugs in the library, not questions!
