### ISSUE TITLE
SaveChanges doesn't remove items from the inner collection

### ISSUE THREAD

**Issue by N0M3N** [Jinjinov/IndexedDB.Blazor#10]
### Library version
1.1.1

### OS & OS version
W11x64 + Edge

### Describe the bug
Hi,
we were storing state of a form (single entity) in local storage but once we added possibility for attachments we hit the wall with size limits so we moved to indexed DB (no need to elaborate on this). 

Originaly it all worked until we found out that opening the DB started to take too long (5-10 seconds) and we are doing it often to keep the data alive. So we reworked our solution to use a single instance of the DB which is created on the application startup instead of creating a new one for each task we perform in the DB.

Then it all stopped working - the in browser DB is good but the one stored in memory keeps track of the removed item(s) with the "Deleted" flag. Sadly when we are trying to get the stored item again we get them all - even the removed ones.

### Code example
We have a storage service, which has these two methods with a property `DB: IndexedDb` with a `Set: IndexedSet` and two methods for Get and Set of the single instance:
```
public Object Get() {
  return DB.Set.SingleOrDefault();
}
public void Set(Object? v) {
  DB.Set.Clear(); /* changes state to Deleted */
    if(v != null)
      DB.Set.Add(v); /* adds new item to the inner collection */ 
  DB.SaveChanges(); /* doesn't remove item from the inner collection but correctly updates the browser's Indexed DB */
}
```
Having the code as follows we end up with exeption 'The input sequence contains more than one element.'

```
Svc.Get(); // returns null
Svc.Set(new {...}) // populates the collection with one item
Svc.Get(); // returns the item
Svc.Set(new {...}) // replaces correctly in browser but wrong in memory
Svc.Get(); // throws exception because the inner collection contains two elements

```

### Expected behavior
After calling the 'Save changes' method on a DB instance - Deleted record should be removed from the inner collection - when reading them again they shouldn't be there.

### Additional context
I went through your code and found out that in the 'SaveChanges' method when resolving the Deleted items they don't get removed from the inner collection

**Comment by Jinjinov** [comment]
This is not my library, I only fixed a few things from https://github.com/Reshiru/Blazor.IndexedDB.Framework

I would suggest that you use https://github.com/amuste/DnetIndexedDb - I started using `DnetIndexedDb`, when I realized that in `Blazor.IndexedDB.Framework` all the data is loaded every time. So far, I am very satisfied with `DnetIndexedDb`.

**Comment by N0M3N** [comment]
Thank you for the suggestion I'll give it a try :)
