### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by fastlink30** [Jinjinov/IndexedDB.Blazor#2]
Hi, i not know how to contact you, so i'll write here

there are plan to update at net5.0?

one question, is possible to define multiple keys? how?

Thanks

**Comment by Jinjinov** [comment]
You can use this in your .NET 5 project without problems.

I didn't write this code, I just fixed some problems that were in the original:
https://github.com/Reshiru/Blazor.IndexedDB.Framework

I just looked at the original code and it looks like you can only have one key:
https://github.com/Jinjinov/IndexedDB.Blazor/blob/main/IndexedDB.Blazor/IndexedDB.Blazor/IndexedDb.cs#L200
