### ISSUE TITLE
Set<> implementation

### ISSUE THREAD

**Issue by fastlink30** [Jinjinov/IndexedDB.Blazor#3]
Hi,
Is possible to have the .Set<> function as in entity framework?
I need this becouse i need to use the same query from indexeddb and ms sql server
with the Set<> function i think i can do this

example;
i must do the same from indexeddb & from mssql using entity framework (base class are different, so i can't do like down here)
ctx.pratica.find(10);

something like this (i think) can solve problem
ctx.Set<pratica>.find(10);

ctx can be dbcontext or IndexedDb (depend what db i must use), for this i need the Set<> (or different solution)

**Comment by Jinjinov** [comment]
I didn't write this code, I just fixed some problems that were in the original code:
https://github.com/Reshiru/Blazor.IndexedDB.Framework

If you want to use the same query from IndexedDB and from MS SQL server, then you should write an interface for data access and use this interface anywhere you want to access your data. Then implement this interface 2 times: 1 time for IndexedDB and 1 time for MS SQL server. Or you can write a Facade (that is a structural design pattern).
