### ISSUE TITLE
Could not find 'TimeGhost.IndexedDbManager.openDb'

### ISSUE THREAD

**Issue by waleed-alharthi** [Jinjinov/IndexedDB.Blazor#4]
### Library version
1.1.1

### OS
Windows 10

### Describe the bug
`Microsoft.JSInterop.JSException: Could not find 'TimeGhost.IndexedDbManager.openDb' ('TimeGhost' was undefined).` error when creating database

### Code
```
@page "/students"
@inject IIndexedDbFactory DbFactory
@implements IDisposable

@code {
    private List<Student> students;
    private IndexedDbContext indexedDbContext;

    protected override async Task OnInitializedAsync()
    {
        indexedDbContext = await this.DbFactory.Create<IndexedDbContext>();
        indexedDbContext.Students.Add(new Student()
        {
            Email = "name@address.com",
            FirstName = "name",
            LastName = "tribe",
            DateOfBirth = DateTime.Now.AddYears(-35)
        });
        await indexedDbContext.SaveChanges();
    }

    public void Dispose()
    {
        indexedDbContext?.Dispose();
    }
}
```

### Exceptions
`Microsoft.JSInterop.JSException: Could not find 'TimeGhost.IndexedDbManager.openDb' ('TimeGhost' was undefined).`
this happens in line:
`indexedDbContext = await this.DbFactory.Create<IndexedDbContext>();`

### Expected behavior
Database gets created and one student added

### Additional context
Using Blazor WASM 5.0 (ASP.NET Core hosted)
Added the service to Client's Program.cs as follows:
`builder.Services.AddSingleton<IIndexedDbFactory, IndexedDbFactory>();`

**Comment by Jinjinov** [comment]
try to run this example:

https://github.com/Jinjinov/IndexedDB.Blazor/tree/main/IndexedDB.Blazor/IndexedDB.Blazor.Example

if this example works, then you forgot to add something to your project
