### ISSUE TITLE
record duplicate/ update problem

### ISSUE THREAD

**Issue by fastlink30** [Jinjinov/IndexedDB.Blazor#5]
### Library version
1.1.1
### OS & OS version
win10 blazor webassembly

### Describe the bug
record not added/updated correctly when connection is opened only at the start of the program.
if i want update the entity, the orginal entity is added and the modified entity 

### To Reproduce
add:
if i open connection add record , close connection and do the same with the 2nd record is all ok

but if i open connection at the start of the program and write 1 record, and after another record, i found 3 record,
the entity are not marked as already added

update:
open connection insert 2 record, update the first record, i found 3 records of the first, and 2 records of the second,
the updated record is part of the group of 3 records

### Additional context
the connection is closed only when application is closed

**Comment by Jinjinov** [comment]
Closed because you didn't provide C# code to reproduce the problem.
