### ISSUE TITLE
Closed because you didn't provide C# code to reproduce the problem.

### ISSUE THREAD

**Issue by fastlink30** [Jinjinov/IndexedDB.Blazor#6]
Closed because you didn't provide C# code to reproduce the problem.

_Originally posted by @Jinjinov in https://github.com/Jinjinov/IndexedDB.Blazor/issues/5#issuecomment-924330051_

**Comment by fastlink30** [comment]
[test_indexeddb.zip](https://github.com/Jinjinov/IndexedDB.Blazor/files/7216354/test_indexeddb.zip)

1 -> start application, click on button add2, look db dd, you found 3 records, all ok.
2 -> press another time button add2, the records already exists also if before on code is executed the .clear()
3 -> delete records enable '2nd test' section, you see that now there are 6 records (not 3 as must be) and the change are applied to 2 records, the original and record added by the library
4 -> disable 2nd test, enable test 3, remove all the records from db, press button 'add2', the record removed is replaced with the prior record
5 -> disable test 3, enable test 4, remove all records on db, press button 'add2', the original record is updated, but also another record is added with the same data

we can't open db, execute operation on db & close db, we need to use 'large' db with indexeddb, and we can't think to use strategy like this, becouse everytime the db is opened read all the records and in our case this means minimum 30secs everytime everytime db open

**Comment by Jinjinov** [comment]
I did not write this library. I only made a few small changes.

The original library is at: https://github.com/Reshiru/Blazor.IndexedDB.Framework

This problem is already in the original library. I don't know how to fix it.

If you don't want to load all records every time, then you have to use this library: https://github.com/wtulloch/Blazor.IndexedDB
