### ISSUE TITLE
Doesn't update inner class objects changes on SaveChanges()

### ISSUE THREAD

**Issue by thepra** [Jinjinov/IndexedDB.Blazor#7]
### Library version
1.1.1

### OS & OS version
Windows 10 x64

### Describe the bug
I followed as in the README documentation, got the interested entity, changed an inner `List` to add a new item in it and then did the `await db.SaveChanges();` without success.

### To Reproduce
```
using (var db = await DbFactory.Create<indexDb>())
{
	var discussion = db.Discussions.First(d => d.Id == CurrentDiscussionId);
	discussion.Answers.Add(newAnswer);
	await db.SaveChanges();
}
```
minimally, a `Discussion` with is `Answers` look like this:
```
public class ViewDiscussion
{
  [Key]
  public string Id { get; set; }
  public List<ViewAnswer> Answers { get; set; } = new();
}
public class ViewAnswer
{
  public string Id { get; set; }
  public short Likes { get; set; } = 0;
  public bool IsMaker { get; set; } = false;
  public string Text { get; set; }
  public DateTime? TimeStamp { get; set; }
  
  [JsonIgnore]
  public bool IsEditingPossible => IsMaker && (Comments.Count == 0 || (TimeStamp == null ? false :
	  (DateTime.Now - TimeStamp.Value).TotalMinutes <= VConstants.AnswerExpirationMinutes));
  
  public List<ViewComment> Comments { get; set; } = new();
}
public class ViewComment
{
  public string Id { get; set; }
  public bool IsMaker { get; set; }
  public string Text { get; set; }
}
```

### Exceptions (if any)
None

### Expected behavior
The `ViewAnswer` is added and stored in the IndexedDB

**Comment by thepra** [comment]
Got what's wrong, it's that `IsEditingPossible` getter which seems to don't work well as an IndexedDB entity. I made it a function and now everything works :)

As a side question, is there any way to mark a property that shouldn't be considered in the IndexedDB transactions?

**Comment by thepra** [comment]
On a second text, now it does seem to don't update the `Comments` list, like in this code:
```
using (var db = await DbFactory.Create<indexDb>())
{
  var discussion = db.Discussions.First(d => d.Id == CurrentDiscussionId);
  discussion.Answers.First(a => a.Id == answerId).Comments.Add(newComment);
  await db.SaveChanges();
}
```
Am I doing something wrong?

**Comment by thepra** [comment]
I may found that deleting, saving, readding and saving the Entity is working :/

**Comment by Jinjinov** [comment]
I didn't write this library, I just made a few small changes.

This library is not as powerful as Entity Framework. I think that it can't handle nested lists.

You can see how I am using it here: https://github.com/Jinjinov/TheLastTime

I am using it with objects that have only simple members, like `bool, int, float, double, string`.

My objects don't save a `List<>` to IndexedDB.

My objects save a foreign key `int parentId` and then I use that to recreate the nested lists after I load the objects.

**Comment by thepra** [comment]
@Jinjinov  I see, so I guess it's luck that it can handle at least lists in a remove/save/add/save flow.
Thanks for the elucidation.
