### ISSUE TITLE
How to remove/drop the table and database from IndexedDB

### ISSUE THREAD

**Issue by imprathamesh** [Jinjinov/IndexedDB.Blazor#8]

**Comment by Jinjinov** [comment]
Clear table:

```
using (var db = await this.DbFactory.Create<ExampleDb>())
{
  db.People.Clear();
  await db.SaveChanges();
}
```

To drop a table or delete the database you will have to access the `TG.Blazor.IndexedDB.IndexedDBManager` from the third party library https://github.com/wtulloch/Blazor.IndexedDB that this library is using:

When you inherit from IndexedDb, you also inherit `protected IndexedDBManager connector;`

```
public class ExampleDb : IndexedDb
{
  public ExampleDb(IJSRuntime jSRuntime, string name, int version) : base(jSRuntime, name, version) { }
  public IndexedSet<Person> People { get; set; }
  
  public async Task DoSomething()
  {
    await this.connector.ClearStore(string storeName); // connector is IndexedDBManager
    await this.connector.DeleteDb(string dbName);
  }
}
```

To see what you can do with `IndexedDBManager` take a look at the third party library:
 https://github.com/wtulloch/Blazor.IndexedDB/blob/master/TG.Blazor.IndexedDb/IndexedDB/IndexedDBManager.cs

`TG.Blazor.IndexedDb` is not my library, I am only using it.
