### ISSUE TITLE
Update browser database schema when new IndexedSet is added

### ISSUE THREAD

**Issue by rainmangilit** [Jinjinov/IndexedDB.Blazor#9]
### Library version
1.1.1

### OS & OS version
Windows 10

### Describe the bug
I added a new IndexedSet<> in code but the store was was not added in the browser indexed db schema. Workaround was to delte the entire indexed db and reload the browser.

**Comment by Jinjinov** [comment]
This is not my library, I only fixed a few things from https://github.com/Reshiru/Blazor.IndexedDB.Framework

I would suggest that you use https://github.com/amuste/DnetIndexedDb

**Comment by rainmangilit** [comment]
Thank you.
